### ISSUE TITLE
Which Keycode to add when adding new entry in gen_mapper_scripts.sh?

### ISSUE THREAD

**Issue by gwatcha** [ggVGc/vimper#1]
Hey, 

I really like vimper, thanks a bunch for making it. I want to add new keys now, I was thinking of adding ()% to be mappable though I am not sure how. I don't know which key code to put into the slot. 

```
 gen "backtick" "\`" 96 0
gen "hook" "¬" 223 5

# My own
gen "openparen" "(" ??? ???
```

Do you have any idea?

Thanks

**Comment by ggVGc** [comment]
Sorry I did not see this issue until now! And I was unaware anyone else than me was actually using vimper :)
Finding the keycodes isn't super straightforward, and the way I do it is to make a mapping with the key I want in reaper, saving it to a temporary file, and then reading what keycode reaper chose for that mapping... This is why I have not mapped every key (since it's some work for each one).
I believe open and close parenthesis might not need new entries though, as they are the combination of shift and another key? Have you tried making such a mapping instead?
I've also noticed some discrepancies between keycodes between osx and windows...
If this is still relevant for you I can make an update.

**Comment by gwatcha** [comment]
No problem, I figured it out and updated it myself. 

I also added a lot more keybindings, checkout my fork if you wish https://github.com/Gwatcha/vimper

I use vimper almost everyday and it is great! Thanks for creating it. When I have the time, I was thinking of adding more features that vim has, like registers, macros, different modes... I love vim bindings and I love music so this project is great lol.

**Comment by ggVGc** [comment]
@Gwatcha Happy to hear :) I had a look at your fork, and looks like you did some nice cleanup and added many new keys.
If you feel like making a PR with the new keys, I will merge it, otherwise I can look into this myself when I get the time.
Thanks for the feedback! It's great to know I'm not the only one who thought this was a good idea :)
And yes, the project is very barebones at the moment. It was basically an attempt at seeing how much usability I could get without much work, but so far it's been working good enough for me so I never revisited it (I also use vimper daily).

**Comment by gwatcha** [comment]
I  won't make a PR, but feel free to merge some things from mine, I'm always adding to it however. No problem for the feedback, vimper's great.
